<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2GMP79\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2GMP79/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerE2GMP79.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerE2GMP79\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerE2GMP79\appAppKernelProdContainer([
    'container.build_hash' => 'E2GMP79',
    'container.build_id' => '2d352813',
    'container.build_time' => 1699868626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2GMP79');
